version: "3"
services:
  cfml:
    container_name: cfml
    image: ortussolutions/commandbox
    restart: always
    environment:
      PORT: 3000
      LUCEE_EXTENSIONS: "3F9DFF32-B555-449D-B0EB5DB723044045;version=1.1.3.1"
    volumes:
      - "./:/app"
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 1m30s
      timeout: 5s
      retries: 10
      start_period: 25s

networks:
  backend:
    driver: bridge
